name: Build

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: orbit-firmware/orbit/.github/workflows/build.yml@master
    with:
      keyboard: feb42
